Features/sign up
wolox-training/mf-react-express pull request #1
Opened 2021-02-03 15:30 UTC by manuelafernandez

## Summary

Sign up screen with a form that allow the users create an account in our platform.

The values that the user have to enter are: 
- First name
- Last name
- Email
- Password
- Password confirmation

When the user press the button ’Sign Up’, in the console you can see the following json:

{
    "email": VALUE,
    "firstName": VALUE,
    "lastName": VALUE,
    "password": VALUE,
    "passwordConfirmation": VALUE,
}

## Screenshots

![image](https://user-images.githubusercontent.com/42481815/106768990-443e0f00-661b-11eb-8dd2-ac881b68596e.png)

## Trello Card
[Sign Up I - Layout](https://trello.com/c/i0BNHnTs/18-sign-up-i-layout)

2021-02-04 19:05 UTC, briangerez requested changes
@manuelafernandez Hi! I gonna to leave some comments 😄 

You can add this file in .gitignore because it isn'n necessary in the project

2021-02-04 19:35 UTC, briangerez requested changes
Excellent work!! 🏆

2021-02-04 19:35 UTC, briangerez commented on src/screens/SignUp/i18n.ts
> +i18next.addResources('es', 'SignUp', {
You should add the English translation.

`i18next.addResources('en', 'SignUp', {
// add all variables in English
});`

2021-02-04 19:35 UTC, briangerez commented on src/screens/SignUp/i18n.ts
> +  password: 'Password',
password: 'Contraseña'

2021-02-04 19:35 UTC, briangerez commented on src/screens/SignUp/i18n.ts
> +  signUp: 'Sign Up'
signUp: 'Registrarse'

"Sign Up" should be English translation! 😄

2021-02-04 19:35 UTC, briangerez commented on src/screens/SignUp/index.tsx
> +      <div className={styles.appForm}>
You can remove any of these divs and put the styles in one

2021-02-04 19:35 UTC, briangerez commented on src/screens/SignUp/index.tsx
> +    console.log(data);
When you add console.log You can put a comment with "Todo" for example:

`//TODO this console.log() will be removed when I develop the integration`

2021-02-04 19:35 UTC, briangerez commented on src/screens/SignUp/index.tsx
> +          <label className={styles.appLabel}>{i18next.t('SignUp:firstName') as string} </label>
For no repeat code, you can create a ARRAY constant (in a file call constants.ts) with the Fields of Form and then you map this. For example: 

in ./constants.ts ->
`export const FIELDS = {
 firstName = 'firstName',
lastName = 'firstName'
.../the rest/...
}:`

in the index.tsx ->

`{FIELDS.map( field => {
<input name={field} ref={register} />
<label className={styles.appLabel}>{i18next.t(`SignUp:${field}`)} </label>
}
)}`

2021-02-04 19:35 UTC, briangerez commented on src/screens/SignUp/styles.module.scss
> +input {
In wolox, we create classnames instead of reference to tags html. For this case, you will can create a style called ".input"

2021-02-08 13:38 UTC, briangerez approved these changes
Excellent!! For the next PR you can remove the .eslintache file of repository 👍

2021-02-08 13:41 UTC, pabloferro requested changes

2021-02-08 13:41 UTC, pabloferro commented on src/screens/SignUp/index.tsx
> +          <div>
Don't disable rules without explaining why. Here you need to add a key to the div, you could use `field`

2021-02-08 13:41 UTC, pabloferro commented on src/screens/SignUp/styles.module.scss
> +  width: 300px;
Be careful with fixed widths.
In this case I'd only fix the width of the container, and let the input grow.

2021-02-10 15:05 UTC, pabloferro approved these changes

2021-02-12 13:09 UTC, merged